In [1]:
import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import os
from pathlib import Path

In [2]:
root_output_directory = "/Users/pp/data/Simulations/A08_SimPHony/swiss/excon_2025_final"
sorted(Path(root_output_directory).iterdir(), key=os.path.getmtime)

[PosixPath('/Users/pp/data/Simulations/A08_SimPHony/swiss/excon_2025_final/.DS_Store'),
 PosixPath('/Users/pp/data/Simulations/A08_SimPHony/swiss/excon_2025_final/big_overview_20_10000p_fine_g1fix_h_kxylem'),
 PosixPath('/Users/pp/data/Simulations/A08_SimPHony/swiss/excon_2025_final/big_overview_20_10000p_fine_g1fix_h_kxylem_HIGH')]

In [5]:
# root_output_directory = "/Users/pp/data/Simulations/A08_SimPHony/swiss/excon"
# scenario_name = "old_params_extensive"

In [3]:
scenario_name = "big_overview_20_10000p_fine_g1fix_h_kxylem_HIGH"
input_path = os.path.join(root_output_directory, scenario_name, 'input')
output_path = os.path.join(root_output_directory, scenario_name, 'output')
post_path = os.path.join(root_output_directory, scenario_name, 'post')

In [4]:
vars = ['psi_leaf_50_close', 'd_50_close','stem_hydraulic_capacitance', 'k_xylem_sat','huber_value',  'leaf_hydraulic_capacitance', 'psi50_xylem' ,'g0', 'g1', 'k_soil_sat0', 'psi_soil_sat0','jackson_root_beta',  'pore_0', 'anet_max', 'root_area_index', 'wcont_sigma_deviation','g_bark']

vars_plant = ['stem_hydraulic_capacitance', 'k_xylem_sat','huber_value', 'leaf_hydraulic_capacitance', 'psi50_xylem' ,'g0','jackson_root_beta']

In [14]:
df = pd.read_csv(os.path.join(post_path, "aggregated_out.csv"))
df.sort_values(by=['RMSE_MAX'], inplace=True, ascending=True)
df = df[df['RMSE_MAX'] < 1.1]
df_grp = df.groupby(['id'])[vars].mean()

In [15]:
df

,Unnamed: 0,index,id,dts,dts_input,verbose,max_psi_leaf_change_per_hour,minimum_psi_leaf_multiplier,conductivity_fraction_type,anet_max,...,t8,t9,t10,t11,t12,t13,alive_mean,target_rmse,RMSE_MAX,sid
2819,3,4915,704,1800.0,1800,False,1.0,4.0,Weibull,0.513100,...,17.634479,17.822093,10.814283,11.329454,10.791598,10.774561,11.904399,0.861927,0.971489,3
2818,2,7252,704,1800.0,1800,False,1.0,4.0,Weibull,0.495855,...,16.415386,16.602072,9.157040,9.570471,9.140500,9.035996,10.271956,0.861927,0.971489,2
2817,1,8741,704,1800.0,1800,False,1.0,4.0,Weibull,0.429825,...,3.691528,3.943155,2.217894,2.393548,2.194478,2.143473,2.502032,0.861927,0.971489,1
2816,0,981,704,1800.0,1800,False,1.0,4.0,Weibull,0.482570,...,0.458795,0.285639,0.467140,0.413967,0.533159,0.435514,0.441831,0.861927,0.971489,0
42613,1,8364,10653,1800.0,1800,False,1.0,4.0,Weibull,0.625365,...,3.629133,3.874057,2.165181,2.340221,2.142541,2.091447,2.448274,0.798771,0.982556,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37800,0,5448,9450,1800.0,1800,False,1.0,4.0,Weibull,0.561836,...,0.289630,0.465052,0.540459,0.516597,0.585903,0.477124,0.527983,0.987874,1.099964,0
5729,1,6178,1432,1800.0,1800,False,1.0,4.0,Weibull,0.977978,...,4.069981,4.414728,2.504123,2.695027,2.479983,2.430041,2.818268,0.921582,1.099966,1
5730,2,6178,1432,1800.0,1800,False,1.0,4.0,Weibull,0.977978,...,4.069981,4.414728,2.504123,2.695027,2.479983,2.430041,2.818268,0.921582,1.099966,2
5728,0,9043,1432,1800.0,1800,False,1.0,4.0,Weibull,0.974682,...,0.287161,0.450016,0.453901,0.444013,0.508114,0.390723,0.463443,0.921582,1.099966,0
5731,3,8058,1432,1800.0,1800,False,1.0,4.0,Weibull,0.768148,...,17.497196,17.684713,10.723006,11.233817,10.700605,10.683357,11.805854,0.921582,1.099966,3

In [16]:
df.loc[df['sid'] == 3,'sid']= 4
df.loc[df['sid'] == 2,'sid']= 3
df['sid']

2819     4
2818     3
2817     1
2816     0
42613    1
        ..
37800    0
5729     1
5730     3
5728     0
5731     4
Name: sid, Length: 21260, dtype: int64

In [17]:
dead_ids =[0,3,6,7]
dfs =df[df['sid'] == 0]
dfs.sort_values(by=['alive_mean'], inplace=True, ascending=True)
dfs.to_csv(os.path.join(post_path, "Alive.csv"))
for i in range(1,5):
    dfs =df[df['sid'] == i]
    dfs.sort_values(by=[f't{dead_ids[i - 1]}'], inplace=True, ascending=True)
    dfs.to_csv(os.path.join(post_path, f"Dead{i}.csv"))

/var/folders/9r/97b9zk_j4ys8v5lnksc4l4j00000gq/T/ipykernel_80001/1464549035.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs.sort_values(by=['alive_mean'], inplace=True, ascending=True)
/var/folders/9r/97b9zk_j4ys8v5lnksc4l4j00000gq/T/ipykernel_80001/1464549035.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs.sort_values(by=[f't{dead_ids[i - 1]}'], inplace=True, ascending=True)

In [18]:
for var in vars:
    fig = plt.figure(figsize=(6,6))
    ax = fig.add_subplot(1,1,1)
    ax.hist(df_grp[var], alpha=1.0, bins = 20)
    ax.set_xlabel(var)
    plt.savefig(f"{post_path}/mean_hist_{var}.png")
    plt.close(fig)

In [19]:
dv = df[vars]
dv['leaf_hydraulic_capacitance'] = np.log10(dv['leaf_hydraulic_capacitance'])
df_norm=(dv-dv.mean())/dv.std()
df_norm['sid'] = df['sid']

/var/folders/9r/97b9zk_j4ys8v5lnksc4l4j00000gq/T/ipykernel_80001/3778912720.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dv['leaf_hydraulic_capacitance'] = np.log10(dv['leaf_hydraulic_capacitance'])

In [20]:
df

,Unnamed: 0,index,id,dts,dts_input,verbose,max_psi_leaf_change_per_hour,minimum_psi_leaf_multiplier,conductivity_fraction_type,anet_max,...,t8,t9,t10,t11,t12,t13,alive_mean,target_rmse,RMSE_MAX,sid
2819,3,4915,704,1800.0,1800,False,1.0,4.0,Weibull,0.513100,...,17.634479,17.822093,10.814283,11.329454,10.791598,10.774561,11.904399,0.861927,0.971489,4
2818,2,7252,704,1800.0,1800,False,1.0,4.0,Weibull,0.495855,...,16.415386,16.602072,9.157040,9.570471,9.140500,9.035996,10.271956,0.861927,0.971489,3
2817,1,8741,704,1800.0,1800,False,1.0,4.0,Weibull,0.429825,...,3.691528,3.943155,2.217894,2.393548,2.194478,2.143473,2.502032,0.861927,0.971489,1
2816,0,981,704,1800.0,1800,False,1.0,4.0,Weibull,0.482570,...,0.458795,0.285639,0.467140,0.413967,0.533159,0.435514,0.441831,0.861927,0.971489,0
42613,1,8364,10653,1800.0,1800,False,1.0,4.0,Weibull,0.625365,...,3.629133,3.874057,2.165181,2.340221,2.142541,2.091447,2.448274,0.798771,0.982556,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37800,0,5448,9450,1800.0,1800,False,1.0,4.0,Weibull,0.561836,...,0.289630,0.465052,0.540459,0.516597,0.585903,0.477124,0.527983,0.987874,1.099964,0
5729,1,6178,1432,1800.0,1800,False,1.0,4.0,Weibull,0.977978,...,4.069981,4.414728,2.504123,2.695027,2.479983,2.430041,2.818268,0.921582,1.099966,1
5730,2,6178,1432,1800.0,1800,False,1.0,4.0,Weibull,0.977978,...,4.069981,4.414728,2.504123,2.695027,2.479983,2.430041,2.818268,0.921582,1.099966,3
5728,0,9043,1432,1800.0,1800,False,1.0,4.0,Weibull,0.974682,...,0.287161,0.450016,0.453901,0.444013,0.508114,0.390723,0.463443,0.921582,1.099966,0
5731,3,8058,1432,1800.0,1800,False,1.0,4.0,Weibull,0.768148,...,17.497196,17.684713,10.723006,11.233817,10.700605,10.683357,11.805854,0.921582,1.099966,4

In [21]:
df_norm

,psi_leaf_50_close,d_50_close,stem_hydraulic_capacitance,k_xylem_sat,huber_value,leaf_hydraulic_capacitance,psi50_xylem,g0,g1,k_soil_sat0,psi_soil_sat0,jackson_root_beta,pore_0,anet_max,root_area_index,wcont_sigma_deviation,g_bark,sid
2819,-0.011716,1.048244,-1.180484,-0.691793,-0.614963,-1.209907,1.012856,-0.382971,0.453594,-0.981078,0.035330,-0.997436,-0.449610,-0.929715,0.476267,-0.792508,-0.733916,4
2818,-0.848153,1.790065,0.059491,-1.235485,-0.832144,-1.594270,1.228173,-0.594581,1.127885,0.942604,0.083758,-0.165071,-1.170499,-1.011457,-0.053609,-0.613764,-0.917141,3
2817,0.744504,0.735909,0.877077,-0.765570,-1.081380,-1.371938,-1.933288,-0.409570,-0.893392,0.255775,1.610266,-0.815696,0.525152,-1.324449,0.087068,-0.936773,-1.065603,1
2816,-0.468073,1.671534,-0.909701,-1.293406,-1.216632,-1.253290,-1.001933,-1.112874,1.204380,0.681584,0.894730,0.466909,-1.016902,-1.074428,0.637134,1.880437,-0.659082,0
42613,0.666928,1.150280,0.856485,-0.127219,-0.929483,-1.356427,1.218943,-1.334891,0.516275,-0.137375,1.811623,-1.003968,-0.299243,-0.397558,0.425452,-0.857342,-1.013115,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37800,0.162835,0.361908,0.235148,1.053373,-0.536359,0.040134,-2.019117,1.381945,0.276948,-0.783658,0.505329,2.140311,1.844545,-0.698695,1.710293,1.321035,1.645325,0
5729,0.781662,0.054731,-0.309391,1.193842,-0.875875,-0.796525,0.869574,-0.783178,-2.166829,-1.136331,1.054649,-0.291190,1.273981,1.273885,-1.367766,-0.616274,-1.172729,1
5730,0.781662,0.054731,-0.309391,1.193842,-0.875875,-0.796525,0.869574,-0.783178,-2.166829,-1.136331,1.054649,-0.291190,1.273981,1.273885,-1.367766,-0.616274,-1.172729,3
5728,-0.103815,0.242240,-1.110656,0.913212,-1.112863,-1.094303,-0.182244,-0.402421,-1.162797,1.889230,1.050412,1.238847,-0.717961,1.258261,-0.500280,1.318302,-1.277828,0
5731,0.791349,-0.004686,-1.499257,1.137065,-0.835027,-0.685237,0.664536,-0.554971,-0.970307,-1.227082,1.232106,-0.504303,-1.297173,0.279255,-0.884109,-0.036825,-0.986681,4

In [22]:
for var in vars:
   #if (var == 'id') | (var == 'sid'):
   #     continue        
    fig = plt.figure(figsize=(10,10))
    for sid in [1,3,4]:
        dfh = pd.DataFrame()
        dfh[var] = df_norm[df_norm['sid'] == sid][var].values - df_norm[df_norm['sid'] == 0][var].values
        ax = fig.add_subplot(2,2,sid)
        ax.hist(dfh[var], alpha=1.0, bins = 20)
        ax.set_xlabel(var)
        ax.text(0.95, 0.95, f"Mean: {np.round(dfh[var].mean(), 4)}",
        verticalalignment ='bottom',
        horizontalalignment ='right',
        transform = ax.transAxes)
    plt.savefig(f"{post_path}/sid_hist_{var}.png")
    plt.close(fig)