In [2]:
import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import os
from pathlib import Path

In [3]:
root_output_directory = "/Users/pp/data/Simulations/A08_SimPHony/swiss/excon_2024_final"
sorted(Path(root_output_directory).iterdir(), key=os.path.getmtime)

[PosixPath('/Users/pp/data/Simulations/A08_SimPHony/swiss/excon_2024_final/big_overview_20_10000p_fine_g1fix_relay'),
 PosixPath('/Users/pp/data/Simulations/A08_SimPHony/swiss/excon_2024_final/big_overview_10_10000p_fine_g1fix')]

In [18]:
# root_output_directory = "/Users/pp/data/Simulations/A08_SimPHony/swiss/excon"
# scenario_name = "old_params_extensive"

In [7]:
scenario_name = "big_overview_20_10000p_fine_g1fix_relay"
input_path = os.path.join(root_output_directory, scenario_name, 'input')
output_path = os.path.join(root_output_directory, scenario_name, 'output')
post_path = os.path.join(root_output_directory, scenario_name, 'post')

In [33]:
vars = ['psi_leaf_50_close', 'd_50_close','stem_hydraulic_capacitance', 'k_xylem_sat','huber_value',  'leaf_hydraulic_capacitance', 'psi50_xylem' ,'g0', 'g1', 'k_soil_sat0', 'psi_soil_sat0','jackson_root_beta',  'pore_0', 'anet_max', 'root_area_index', 'wcont_sigma_deviation','g_bark']

vars_plant = ['stem_hydraulic_capacitance', 'k_xylem_sat','huber_value', 'leaf_hydraulic_capacitance', 'psi50_xylem' ,'g0','jackson_root_beta']

In [34]:
df = pd.read_csv(os.path.join(post_path, "aggregated_out.csv"))
df.sort_values(by=['RMSE_MAX'], inplace=True, ascending=True)
df = df[df['RMSE_MAX'] < 1.0]
df_grp = df.groupby(['id'])[vars].mean()

In [35]:
df

,Unnamed: 0,index,id,dts,dts_input,verbose,max_psi_leaf_change_per_hour,minimum_psi_leaf_multiplier,conductivity_fraction_type,anet_max,...,t8,t9,t10,t11,t12,t13,alive_mean,target_rmse,RMSE_MAX,sid
104559,3,915,26139,1800.0,1800,False,1.0,4.0,Weibull,0.220560,...,18.004893,18.192764,11.016093,11.537310,10.993229,10.976883,12.130541,0.784787,0.832763,3
104556,0,5898,26139,1800.0,1800,False,1.0,4.0,Weibull,0.314535,...,0.377711,0.304706,0.402944,0.380045,0.456323,0.368326,0.398317,0.784787,0.832763,0
104557,1,4232,26139,1800.0,1800,False,1.0,4.0,Weibull,0.236181,...,3.792128,4.503499,2.408765,2.588272,2.390498,2.331284,2.745623,0.784787,0.832763,1
104558,2,276,26139,1800.0,1800,False,1.0,4.0,Weibull,0.295565,...,16.841502,17.028528,9.367543,9.786458,9.351226,9.245170,10.512932,0.784787,0.832763,2
72527,3,1045,18131,1800.0,1800,False,1.0,4.0,Weibull,0.391930,...,18.506551,18.694754,11.335852,11.870967,11.312785,11.296671,12.478549,0.781737,0.836669,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71347,3,4662,17836,1800.0,1800,False,1.0,4.0,Weibull,0.288846,...,19.501125,19.689934,11.967040,12.528667,11.943527,11.927601,13.165536,0.819534,0.999990,3
31851,3,3922,7962,1800.0,1800,False,1.0,4.0,Weibull,0.365807,...,17.350675,17.538085,10.662797,11.174855,10.638043,10.622583,11.733753,0.820839,0.999993,3
31850,2,3894,7962,1800.0,1800,False,1.0,4.0,Weibull,0.441238,...,16.572677,16.759492,9.256410,9.676240,9.237632,9.137413,10.381085,0.820839,0.999993,2
31849,1,9435,7962,1800.0,1800,False,1.0,4.0,Weibull,0.386380,...,3.581161,3.868925,2.163363,2.340991,2.135771,2.087690,2.445477,0.820839,0.999993,1
31848,0,1959,7962,1800.0,1800,False,1.0,4.0,Weibull,0.387052,...,0.383974,0.299489,0.405189,0.387532,0.458594,0.371737,0.402856,0.820839,0.999993,0

In [45]:
df.loc[df['sid'] == 3,'sid']= 4
df.loc[df['sid'] == 2,'sid']= 3
df['sid']

104559    4
104556    0
104557    1
104558    3
72527     4
         ..
71347     4
31851     4
31850     3
31849     1
31848     0
Name: sid, Length: 22140, dtype: int64

In [46]:
dead_ids =[0,3,6,7]
dfs =df[df['sid'] == 0]
dfs.sort_values(by=['alive_mean'], inplace=True, ascending=True)
dfs.to_csv(os.path.join(post_path, "Alive.csv"))
for i in range(1,5):
    dfs =df[df['sid'] == i]
    dfs.sort_values(by=[f't{dead_ids[i - 1]}'], inplace=True, ascending=True)
    dfs.to_csv(os.path.join(post_path, f"Dead{i}.csv"))

/var/folders/9r/97b9zk_j4ys8v5lnksc4l4j00000gq/T/ipykernel_24607/1464549035.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs.sort_values(by=['alive_mean'], inplace=True, ascending=True)
/var/folders/9r/97b9zk_j4ys8v5lnksc4l4j00000gq/T/ipykernel_24607/1464549035.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfs.sort_values(by=[f't{dead_ids[i - 1]}'], inplace=True, ascending=True)

In [38]:
for var in vars:
    fig = plt.figure(figsize=(6,6))
    ax = fig.add_subplot(1,1,1)
    ax.hist(df_grp[var], alpha=1.0, bins = 20)
    ax.set_xlabel(var)
    plt.savefig(f"{post_path}/mean_hist_{var}.png")
    plt.close(fig)

In [49]:
dv = df[vars]
dv['leaf_hydraulic_capacitance'] = np.log10(dv['leaf_hydraulic_capacitance'])
df_norm=(dv-dv.mean())/dv.std()
df_norm['sid'] = df['sid']

/var/folders/9r/97b9zk_j4ys8v5lnksc4l4j00000gq/T/ipykernel_24607/3778912720.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dv['leaf_hydraulic_capacitance'] = np.log10(dv['leaf_hydraulic_capacitance'])

In [50]:
df

,Unnamed: 0,index,id,dts,dts_input,verbose,max_psi_leaf_change_per_hour,minimum_psi_leaf_multiplier,conductivity_fraction_type,anet_max,...,t8,t9,t10,t11,t12,t13,alive_mean,target_rmse,RMSE_MAX,sid
104559,3,915,26139,1800.0,1800,False,1.0,4.0,Weibull,0.220560,...,18.004893,18.192764,11.016093,11.537310,10.993229,10.976883,12.130541,0.784787,0.832763,4
104556,0,5898,26139,1800.0,1800,False,1.0,4.0,Weibull,0.314535,...,0.377711,0.304706,0.402944,0.380045,0.456323,0.368326,0.398317,0.784787,0.832763,0
104557,1,4232,26139,1800.0,1800,False,1.0,4.0,Weibull,0.236181,...,3.792128,4.503499,2.408765,2.588272,2.390498,2.331284,2.745623,0.784787,0.832763,1
104558,2,276,26139,1800.0,1800,False,1.0,4.0,Weibull,0.295565,...,16.841502,17.028528,9.367543,9.786458,9.351226,9.245170,10.512932,0.784787,0.832763,3
72527,3,1045,18131,1800.0,1800,False,1.0,4.0,Weibull,0.391930,...,18.506551,18.694754,11.335852,11.870967,11.312785,11.296671,12.478549,0.781737,0.836669,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71347,3,4662,17836,1800.0,1800,False,1.0,4.0,Weibull,0.288846,...,19.501125,19.689934,11.967040,12.528667,11.943527,11.927601,13.165536,0.819534,0.999990,4
31851,3,3922,7962,1800.0,1800,False,1.0,4.0,Weibull,0.365807,...,17.350675,17.538085,10.662797,11.174855,10.638043,10.622583,11.733753,0.820839,0.999993,4
31850,2,3894,7962,1800.0,1800,False,1.0,4.0,Weibull,0.441238,...,16.572677,16.759492,9.256410,9.676240,9.237632,9.137413,10.381085,0.820839,0.999993,3
31849,1,9435,7962,1800.0,1800,False,1.0,4.0,Weibull,0.386380,...,3.581161,3.868925,2.163363,2.340991,2.135771,2.087690,2.445477,0.820839,0.999993,1
31848,0,1959,7962,1800.0,1800,False,1.0,4.0,Weibull,0.387052,...,0.383974,0.299489,0.405189,0.387532,0.458594,0.371737,0.402856,0.820839,0.999993,0

In [51]:
df_norm

,psi_leaf_50_close,d_50_close,stem_hydraulic_capacitance,k_xylem_sat,huber_value,leaf_hydraulic_capacitance,psi50_xylem,g0,g1,k_soil_sat0,psi_soil_sat0,jackson_root_beta,pore_0,anet_max,root_area_index,wcont_sigma_deviation,g_bark,sid
104559,0.664393,1.453754,-0.065152,-0.916166,-0.878271,-0.987871,-0.581013,-0.196032,-1.364280,0.703438,0.752403,-0.464414,-1.074865,-1.064315,1.380375,-0.710822,-0.045214,4
104556,0.862490,0.737713,-0.009706,-0.737465,-2.058413,-1.131994,-0.398501,-0.270789,-1.318670,0.359402,-1.754287,2.007591,1.338959,-0.659998,1.448529,1.372661,-0.704558,0
104557,-0.528073,1.292643,1.275201,-0.589886,-0.579377,-1.247751,-0.262674,-0.344223,-1.446948,-1.324837,1.308840,-0.971336,-0.392711,-0.997107,0.051684,0.114857,0.229768,1
104558,-0.134810,0.635381,1.324240,-0.868757,-0.818408,-1.149928,0.809081,-0.673188,-1.097084,-0.173672,0.478120,-0.806572,-1.366522,-0.741615,-0.179033,-0.273160,0.112994,3
72527,-0.764626,0.627324,-0.432484,-0.586812,0.263838,-1.512411,-1.007518,0.411968,-1.417820,-1.264491,0.090374,-1.016828,-0.817097,-0.327018,0.355123,-0.103164,0.600775,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71347,0.403398,0.382309,-0.942583,0.566998,-1.008587,0.506504,-0.918123,-0.914760,0.490868,1.146820,0.609528,-0.520901,-1.000282,-0.770522,-1.845004,-0.736266,-0.086075,4
31851,-0.169026,-0.929386,-0.932101,1.521877,-2.037575,1.216478,0.573650,-0.959835,0.923508,-1.354851,0.595685,0.258984,1.111142,-0.439409,-1.136486,-0.675638,-1.466600,4
31850,-0.589198,-0.553465,1.030255,0.886185,-2.036386,1.091650,1.078665,-0.972818,2.000605,-0.814142,0.741614,-0.709994,1.210147,-0.114875,-0.498830,-0.802917,-0.847893,3
31849,0.466258,-0.686927,0.176983,1.495291,-1.119886,0.928444,-0.725890,-1.307328,0.394325,0.543845,1.309380,-0.969711,-0.864882,-0.350893,-0.711871,-0.363516,-0.793370,1
31848,0.784312,-0.553307,0.768301,0.809141,-1.994110,0.891846,0.240330,-0.975385,1.501601,1.038326,-0.430437,1.277178,0.460842,-0.348003,-0.064734,1.411888,-1.638954,0

In [52]:
for var in vars:
   #if (var == 'id') | (var == 'sid'):
   #     continue        
    fig = plt.figure(figsize=(10,10))
    for sid in [1,3,4]:
        dfh = pd.DataFrame()
        dfh[var] = df_norm[df_norm['sid'] == sid][var].values - df_norm[df_norm['sid'] == 0][var].values
        ax = fig.add_subplot(2,2,sid)
        ax.hist(dfh[var], alpha=1.0, bins = 20)
        ax.set_xlabel(var)
        ax.text(0.95, 0.95, f"Mean: {np.round(dfh[var].mean(), 4)}",
        verticalalignment ='bottom',
        horizontalalignment ='right',
        transform = ax.transAxes)
    plt.savefig(f"{post_path}/sid_hist_{var}.png")
    plt.close(fig)